minimumReleaseAgeExclude:
  - "@ai-sdk/*"
  - "@rolldown/*"
  - "@vercel/*"
  - "@workflow/*"
  - ai
  - experimental-ai-sdk-code-mode
  - eve
  - nitro
  - rolldown
  - workflow
allowBuilds:
  sharp: false
